version: '3.8'

services:
  postgres:
    image: postgres:latest 
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5732:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  n8n: #
    image: docker.n8n.io/n8nio/n8n 
    restart: always 
    depends_on: 
      - postgres
    ports: 
      - "5699:5678"
    volumes: 
      - n8n_data:/home/node/.n8n
    environment: 
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: ${N8N_PORT}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      N8N_DATABASE_TYPE: ${N8N_DATABASE_TYPE}
      N8N_DATABASE_POSTGRESDB_DATABASE: ${N8N_DATABASE_POSTGRESDB_DATABASE}
      N8N_DATABASE_POSTGRESDB_USER: ${N8N_DATABASE_POSTGRESDB_USER}
      N8N_DATABASE_POSTGRESDB_PASSWORD: ${N8N_DATABASE_POSTGRESDB_PASSWORD}
      N8N_DATABASE_POSTGRESDB_HOST: ${N8N_DATABASE_POSTGRESDB_HOST}
      N8N_DATABASE_POSTGRESDB_PORT: ${N8N_DATABASE_POSTGRESDB_PORT}

volumes: 
  n8n_data: 
    driver: local
  postgres-data: 
    driver: local
